log_level = "warn"
outputs = "All"
position = "Top"
enable_esc_key = true

[modules]
left = [ "AppLauncher", "Workspaces" ]
center = [ "WindowTitle" ]
right = [ "Tray", "MediaPlayer", "Settings", "Clock" ]

[window_title]
mode = "Title"
truncate_title_after_length = 75

[settings]
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueman-manager"
remove_airplane_btn = true
remove_idle_btn = true

[[CustomModule]]
name = "AppLauncher"
icon = "󱗼"
command = "walker"

[[CustomModule]]
name = "Notifications"
icon = ""
command = "swaync-client -t -sw"
listen_cmd = "swaync-client -swb"
icons.'dnd.*' = ""
alert = ".*notification"
