excludes = [
    "**/dunst/*",
    "**/kdedefaults/*",
    "*.png",
    "*.conf",
    "*.gitignore",
    "*.toml",
    "Makefile",
    "**/waybar/themes/ml4w-minimal/style.css",
]

[formatter.nixfmt-rfc-style]
command = "nixfmt"
includes = ["*.nix"]

[formatter.shellcheck]
command = "shellcheck"
includes = ["*.sh"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
 "*.css",
 "*.scss",
 "*.md",
 "*.yaml",
 "*.json",
 "*.jsonc",
]
